### ISSUE TITLE
Spit shine that bitch

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com_v2#2]
1. match font styling, the styles are in figma file. If you are using the expected h1, h2, h3, p = given styling, the following should be h1, h2, etc.

![image](https://user-images.githubusercontent.com/5694308/59174413-7879d780-8b7b-11e9-84e5-e906881475a4.png)

2. images should have rounded corners : `border-radius: 3px;`

3. the hero image container should have a double box shadow (not the image, the container, shadow should barely show under the image giving it a raised look:

```
box-shadow: 0px 9px 24px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25);
transform: matrix(-1, 0, 0, 1, 0, 0);
```

4. hero image is missing a half linear gradient making book your nature retreat easier to read. The gradient also ends halfway at the image, which is where the text should be aligned (currently the h1 in hero image is not placed correctly:

```
background: linear-gradient(0deg, #191C21 0%, rgba(25, 28, 33, 0) 50%), 
transform: matrix(-1, 0, 0, 1, 0, 0);
```

5. proportions on listing image is off, should be wider and less tall. In the design file the size is w:280px h:150 , so keep those constraints. For reference, the entire listing container is w280 h240
![image](https://user-images.githubusercontent.com/5694308/59174722-b7f4f380-8b7c-11e9-9aba-9c21ac0c8079.png)

6. footer should not have a stroke, but a minor shadow instead: `box-shadow: 0px -1px 0px #121416;`

7. responsive issues on mobile. Some of this is font styling. Also need show all button and dividers here.

Target: 
![image](https://user-images.githubusercontent.com/5694308/59174863-541efa80-8b7d-11e9-9d29-071ea9d5a913.png)

![image](https://user-images.githubusercontent.com/5694308/59174879-65680700-8b7d-11e9-83ad-2dc1167bd29e.png)

**Comment by paulchrisluke** [comment]
I also updated the button styles for the button components, adding shadow, stroke... I also added a chevron >

Green button:

```
background: #4B7F52;
border: 1px solid #FFFFFF;
box-sizing: border-box;
box-shadow: 0px 9px 24px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 4px;
```

white button:
```

border: 1px solid #FFFFFF;
box-sizing: border-box;
box-shadow: 0px 9px 24px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 4px;
```

**Comment by paulchrisluke** [comment]
also distances in grid. You can see distances between items in figma by holding alt and moving the curser around your question area. For example, the distance between listings is 30px:

![image](https://user-images.githubusercontent.com/5694308/59175091-6a798600-8b7e-11e9-93cf-67f617e0c856.png)

**Comment by paulchrisluke** [comment]
entire box should be clickable, not just the image on listing, or just the buttons on the larger items.

![image](https://user-images.githubusercontent.com/5694308/59175451-cee91500-8b7f-11e9-95ad-e089ac7d9cc3.png)

**Comment by paulchrisluke** [comment]
nav bar changes:

missing drop shadow making it appear lifted above: `box-shadow: 0px 1px 0px #121416;`

add more padding top/bottom of logo: `15px`

**Comment by atharva3010** [comment]
okay

**Comment by paulchrisluke** [comment]
reviewed:

https://github.com/whynotearth/vkirirom.com_v2/issues/2#issuecomment-500298992
https://github.com/whynotearth/vkirirom.com_v2/issues/2#issuecomment-500301805

these two issues remain, also add max width of site to 900px and align everything on those lines. Should solve proportion and responsive issues

**Comment by paulchrisluke** [comment]
-add show all button under experiences
- can we fit 3 blog posts in width on tablet?
- add "blog" to nav

**Comment by paulchrisluke** [comment]
- can we keep 10px distance here on tablet?
![image](https://user-images.githubusercontent.com/5694308/59322381-139bba00-8d00-11e9-8673-1ca905d7da2f.png)

- update footer to match figma titles

- nav bar is missing

- direct urls 404

-center on mobile:
![image](https://user-images.githubusercontent.com/5694308/59322433-46de4900-8d00-11e9-9ba0-dbf5adcae7dd.png)
