### ISSUE TITLE
[icebox] re design header

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com_v2#41]
re design header area on home page (new font maybe?)

**Comment by paulchrisluke** [comment]
probably want to change the dark grey gradient to look better with green tone
new font? New header image?

**Comment by bamboochow** [comment]
gradient changed, potentially "oswald, regular, size depending on banner/header", also, all banner font changed for consistency.
not done yet. still playing around.

**Comment by atharva3010** [comment]
@bamboochow let me know when you are done so that I can update those changes.

**Comment by bamboochow** [comment]
Done - reminder ALL banners are changed for font to Oswald, not just header

**Comment by atharva3010** [comment]
Great, thank you @bamboochow .

**Comment by atharva3010** [comment]
The design changes have been implemented
