### ISSUE TITLE
Contact form changes

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com_v2#49]
"Full name" placeholder is in every field.

Lets also stick with a single form style (input fields should ideally be styled as a single component that is reused through the site. I like the style of the listing page:

https://cranky-nightingale-3731fc.netlify.com/Contact

I know we gave the ux file for this @bamboochow will change the form in the file to match as well (sorry!)

**Comment by bamboochow** [comment]
@atharva3010 
- fixed booking form for consistency (design details, stroke, etc) 
-scaled down size to fit current info boxes
should be standard for future forms for this site

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/59812203-56304880-9337-11e9-8284-cdddf2dba1c6.png)


alignment, make sure these are all on the same left line

**Comment by paulchrisluke** [comment]
also autofill, is there a better way to handle the background color indicator so it doesn't look as bad?

![image](https://user-images.githubusercontent.com/5694308/59812318-b7581c00-9337-11e9-87d5-79a3bad1f83f.png)

**Comment by atharva3010** [comment]
![image](https://user-images.githubusercontent.com/34229217/59871111-68040100-93b4-11e9-9d9f-03ef90237981.png)  
alignment fixed.  
autofill has also been fixed, it works fine on localhost but it doesn't work when deployed.
