### ISSUE TITLE
add google maps link on /contact

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com_v2#52]
single "get directions" as a blue color works (under the city) 

@bamboochow will update the figma file and then handoff

**Comment by paulchrisluke** [comment]
also remove redundant contact while we at it:

![image](https://user-images.githubusercontent.com/5694308/59731435-531e5500-9270-11e9-9653-d843169c9e14.png)

**Comment by bamboochow** [comment]
@atharva3010 
-Added in "get directions" link
-Removed Contact title
-Changed color of message box

**Comment by atharva3010** [comment]
Okay, thank you @bamboochow .  
Changes updated @paulchrisluke, closing issue.
