### ISSUE TITLE
implement cloudinary api image optimization

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com_v2#61]
https://cloudinary.com/documentation/image_optimization

(you may need logins for this, I can get them for you).

I'm trying to attack the lighthouse audit

**Comment by atharva3010** [comment]
Okay.

**Comment by atharva3010** [comment]
append `/dpr_auto/w_auto/q_auto:low/f_auto/` after `image/upload/` in the cloudinary image links in the db to optimize them.  
  
This will do the following:
1. Deliver a higher resolution image for devices which have larger screen size
2. Deliver a lower resolution image for devices which have lower screen size
3. the highest quality of the image will also be at most 1/4th of the original image
4. the image will be delivered in next gen formats if the browser supports it
so as to optimise the image
for instance, in chrome, opera, mozilla, it will be delivered as webp
to further decrease image size

**Comment by atharva3010** [comment]
done, closing issue
