### ISSUE TITLE
ecommerce - add variation support

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com_v2#62]
Basically, we have a single item type : Bungalow, which has a size variation of 2 twins or a 1 queen bed. This needs to be treated like ecommerce variations, where you would have a single item type: SHIRT, which has size variations of small/medium/large.

Users need to be able to select that variation in the booking form, like you would in ecommerce selection.

**Comment by bamboochow** [comment]
Button created for both variations for 1 queen and 2 twins, button placement in booking area in columns of 2, so if there's 3 options it would just be the next row?, plus additional action visuals (colors invert when selected), you can find that underneath original component (not on listing page) 
@atharva3010

**Comment by bamboochow** [comment]
actually if possible, if you can make the visuals transparent that would be really convenient when using this for different backgrounds
so for pressed actions, instead of a specific color, the text and icon would just be whatever the background color is already on the page?

**Comment by atharva3010** [comment]
the type of beds are pulled from api, so it can change, we can have different no. of beds, both twins and queen. @paulchrisluke currently, there's only one type of bed in the api. Can you make the entry for both?
Fill the value for the ones that are available and "0" for those which aren't available, so that I can use it to enable or disable buttons.

**Comment by atharva3010** [comment]
@bamboochow you want the buttons to be depressed when clicked?

**Comment by bamboochow** [comment]
Maybe not, lets just put it as inverted colors for now

**Comment by atharva3010** [comment]
okay

**Comment by atharva3010** [comment]
design updated
